name: Deploy to Vercel

on:
  push:
    branches:
      - main  # or the branch you want to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@3
        with:
          python-version: '3.9'  # Change this to match your Python version

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Build project
        run: |
          . venv/bin/activate
          # Add any build steps if necessary

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel --prod --token=$VERCEL_TOKEN --confirm
